### ISSUE TITLE
Support mobile urls

### ISSUE THREAD

**Issue by rastasheep** [ArunMichaelDsouza/ng-youtube-embed#12]
Current version of ng-youtube-embed doesn't play well with mobile urls as video src
For example:
'https://www.youtube.com/watch?v=E813VYySueM' => works as expected
'https://m.youtube.com/watch?v=E813VYySueM' => broken

**Comment by ArunMichaelDsouza** [comment]
Thanks for reporting this issue, it has been fixed in [v1.7.10](https://github.com/ArunMichaelDsouza/ng-youtube-embed/releases/tag/v1.7.10)
