### ISSUE TITLE
Dynamic data for VideoId is not working for stopping/playing the player from controller

### ISSUE THREAD

**Issue by rui7999** [ArunMichaelDsouza/ng-youtube-embed#14]
Hi @ArunMichaelDsouza,

if i added dynamic scope value to videoId in the html, and access it through controller for stopping and playing the video is not working. It is so flaky, it works some times and it doesn't works sometimes and i can see console errors for  player. any functions are not defined.

I changed your code pen demo with scope for videoId. it works first time when you opened the below pen and click on 'playVideo' button and then it doesn't works when you refresh the page or second time when you click on 'playVideo'. DO we need to remove any instance from the Dom, not sure what is going on?

https://codepen.io/anon/pen/gRXKwj

**Comment by rui7999** [comment]
@ArunMichaelDsouza: i had seen an email that you asked for code snippet. I already gave a code pen and explained the bug in previous post. Wondering can you take a look please as i have been waiting for long time on this/

**Comment by ArunMichaelDsouza** [comment]
Hi, apologies for the late reply. Are you still working on it ?
