### ISSUE TITLE
No audio iOS silent mode

### ISSUE THREAD

**Issue by Pseudo-Nym** [ArunMichaelDsouza/ng-youtube-embed#15]
I have noticed that on an iOS device, if the ringer is turned off the audio for an embedded video is muted. Turning off silent/turning the ringer back on (hardware toggle) and the audio works as expected.

**Comment by ArunMichaelDsouza** [comment]
I tried it on my iOS device, and it seems to be working fine. Anything that I might have missed ?

**Comment by Pseudo-Nym** [comment]
I'm using an iPhone 7 Plus on iOS 10.1.1 when I have hardware silent toggled, on the side of the phone, I get no audio. Same on iPad Air 2 on iOS 10.3.3... Also same behavior on an iPhone 6 on 10.3.3.

Note this is happening when using in a hybrid app Ionic 1.3.3, Cordova 7.0.1, Angular 1.5.3

**Comment by Pseudo-Nym** [comment]
Also same behavior on an iPhone 6 on 10.3.3

**Comment by Pseudo-Nym** [comment]
Also note this is happening when using in a hybrid app Ionic v1, Cordova, Angular 1
