### ISSUE TITLE
Angularjs2 Implementation

### ISSUE THREAD

**Issue by mohinithorat** [ArunMichaelDsouza/ng-youtube-embed#16]
Can you just help me out to implement video player for youtube source in angularjs2.

Or can suggest any other plugin for the same.

**Comment by ArunMichaelDsouza** [comment]
``ng-youtube-embed`` is meant to work only with ``AngularJS 1.x``. You can try the following alternatives for your ``Angular 2`` app - 

https://www.npmjs.com/package/ng2-youtube-player
https://www.npmjs.com/package/ng2-youtube
