### ISSUE TITLE
autoplay doesn't work on mobile devices

### ISSUE THREAD

**Issue by tapway** [ArunMichaelDsouza/ng-youtube-embed#17]
autoplay working perfectly on desktop but not mobile devices (both Android and iOS). Any workaround?

**Comment by ArunMichaelDsouza** [comment]
Seems like its not supported by all mobile devices. Read here - https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations

**Comment by rezarat** [comment]
Any update yet on this issue?

**Comment by pettrushkov** [comment]
> Any update yet on this issue?

no

**Comment by ArunMichaelDsouza** [comment]
Please check here - https://developers.google.com/youtube/iframe_api_reference#Mobile_considerations
