### ISSUE TITLE
Documentation on Events

### ISSUE THREAD

**Issue by Kookpot** [ArunMichaelDsouza/ng-youtube-embed#21]
Hi,

I'm using your component but lost a lot of time on making the events work.
Your documentation never mentions that supplying a videoid is mandatory before the events can work.
In your example, there is mention of video but not videoid.

Can the documentation be changed for this to avoid other people breaking their heads on this?

Thanks.

P.S.: Kudos on the component

**Comment by ArunMichaelDsouza** [comment]
Hi @Kookpot. Its already mentioned in the documentation. Please check - 

![screen shot 2018-03-10 at 4 00 15 am](https://user-images.githubusercontent.com/4924614/37233091-d57922a0-2417-11e8-9f8f-1a0281e55c38.png)

**Comment by Kookpot** [comment]
Then also mention this parameter here please : 
![image](https://user-images.githubusercontent.com/6267152/37251236-85bab38c-250c-11e8-94d3-66895ea3d457.png)

This example will NOT work as there is no videoid parameter given. Kinda strange to have an example of events that does not work.
Also note that you use videoID as variable when there is actually a videoid parameter. Very confusing!!

**Comment by ArunMichaelDsouza** [comment]
Oh yes! My apologies for not catching that. The documentation has been corrected. Thank you!
