### ISSUE TITLE
Stop video

### ISSUE THREAD

**Issue by Steco17** [ArunMichaelDsouza/ng-youtube-embed#22]
Hi, i have been having issues trying to write an angular function to stop the video. i can't see any example in you documentation please you i get some help here. i'll appreciate if you provide me with an example. i tried this but nothing and i can't find any help online

$scope.stopVid = function(){			
	var player = ngYoutubeEmbedService.getPlayerById('myvideo');
   	 player.stopVideo();	
}

**Comment by ArunMichaelDsouza** [comment]
Hi, I tried your code sample and it seemed to be working fine. I hope the ``videoid`` parameter is correctly used with the value of ``myvideo``.
