### ISSUE TITLE
Angular dependency how to

### ISSUE THREAD

**Issue by guetstudio** [ArunMichaelDsouza/ng-youtube-embed#25]
More than likely a stupid question but I'm using angular and have a app.module.ts file so not sure about how to convert: 
var myApp = angular.module('myApp', ['ngYoutubeEmbed']);
into... ?

I have tried:

```
import { ngYoutubeEmbed } from 'ng-youtube-embed';
@NgModule({
imports: [
    ngYoutubeEmbed.forRoot()
]
})
export class AppModule { }
```
but still getting an error:
Uncaught ReferenceError: angular is not defined
    at ng-youtube-embed.min.js:7
    at Object../node_modules/ng-youtube-embed/build/ng-youtube-embed.min.js (ng-youtube-embed.min.js:7)

any help will be much appreciated!

Thanks,

**Comment by ArunMichaelDsouza** [comment]
If you are using ``Angular 2``, you can try the following alternatives for your app -
https://www.npmjs.com/package/ng2-youtube-player
https://www.npmjs.com/package/ng2-youtube

``ng-youtube-embed`` is meant to work only with ``AngularJS 1.x``.

**Comment by guetstudio** [comment]
man I'm sorry, only now saw your reply. Thought I'd get an email if someone replied. Thank you, and sorry again. I'm guessing I should close this now. hope it doesn't blow up on me.
