### ISSUE TITLE
How Can I access YTPlayer functions

### ISSUE THREAD

**Issue by rastamansp** [ArunMichaelDsouza/ng-youtube-embed#4]
Hi, i want to use your module, but i cant access YT methods, I look something about in https://developers.google.com/youtube/js_api_reference?hl=pt-br

ENABLE enablejsapi please

**Comment by ArunMichaelDsouza** [comment]
Will adding the `enablejsapi` parameter to the available options work ?
https://developers.google.com/youtube/player_parameters#enablejsapi

**Comment by ArunMichaelDsouza** [comment]
Hey @rastamansp, 

Support for Youtube JavaScript API for iframe embeds has been added in the [latest version](https://github.com/ArunMichaelDsouza/ng-youtube-embed/releases) of the library i.e. ``1.7.8``. Please check the documentation for more info.
