### ISSUE TITLE
strict mode error on Safari

### ISSUE THREAD

**Issue by sinedied** [ArunMichaelDsouza/ng-youtube-embed#5]
When executing my code on Safari (Mac OS X), I get the following error:

```
[Error] SyntaxError: Strict mode does not allow function declarations in a lexically nested statement. (fonction anonyme) (ng-youtube-embed.js:39)
```

Seems there is a strict mode violation in your code that makes it crash on Safari. (For info, Chrome doesn't bother)

**Comment by ArunMichaelDsouza** [comment]
Can you please tell me which version of the library you are using ? This was recently fixed. Please check pull request [#3](https://github.com/ArunMichaelDsouza/ng-youtube-embed/pull/3). Try updating your library to version `0.3.3`

**Comment by sinedied** [comment]
Indeed, I was using `0.2.4` sorry!

I updated to `0.3.3` and it works fine, thanks.

**Comment by ArunMichaelDsouza** [comment]
Sure! No prob.
