### ISSUE TITLE
Youtube Gaming support

### ISSUE THREAD

**Issue by Eruyome** [ArunMichaelDsouza/ng-youtube-embed#6]
Hey, can you support the Youtube Gaming url `https://gaming.youtube.com/watch?v=` instead of just the normal url `https://www.youtube.com/watch?v=`?

Thanks in advance.

**Comment by ArunMichaelDsouza** [comment]
@Eruyome I will be adding a new parameter - `gaming` which will have two possible values `true` or `false`, based on which the directive will switch between the `iframe` embed code urls. This feature will be released in the latest version.

**Comment by ArunMichaelDsouza** [comment]
@Eruyome check out the latest [release (v0.4.3)](https://github.com/ArunMichaelDsouza/ng-youtube-embed/releases/tag/v0.4.3).
