### ISSUE TITLE
Uncaught ReferenceError: ytcfg is not defined

### ISSUE THREAD

**Issue by roncodingenthusiast** [ArunMichaelDsouza/ng-youtube-embed#7]
I have an `ng-repeat` of questions and on click it moves to the next question.
```
<div style="display:{{(activeQuestion === $index) ? 'block' : 'none' }}" class="row" ng-repeat="myQuestion in myQuestions">
	<div ng-if="myQuestion.video_url !== undefined">
		<ng-youtube-embed url="myQuestion.video_url"  autoplay="true" color="white" disablekb="true" end="20"></ng-youtube-embed>
	</div>
       <div class="col-sm-12" style="font-size:32px;"><strong>Question:</strong> {{myQuestion.text}    
      </div>
	<button ng-click="selectContinue()">Continue</button>
</div>
		
	</div>
```
Here i have a controller: 

```
var app = angular.module('angularMainApp', ['ngRoute', 'ngYoutubeEmbed']);
app.controller('quizctrl', ['$scope', function($scope){

	$http.get('/somlink/quizdata.php').then(function(quizdata){
		$scope.myQuestions = quizdata.data;
		$scope.totalQuestions = $scope.myQuestions.length;
	});
}]);
```
Here is the error I am getting in my console. Though the video is loading fine and everything works, I am wondering if the error could be fixed. 

![image](https://cloud.githubusercontent.com/assets/7438896/20323862/7e5cdd26-ab4c-11e6-9b14-7552c7608114.png)

**Comment by ArunMichaelDsouza** [comment]
Seems to be an issue with the YouTube iframe embed api - 

http://stackoverflow.com/questions/40622204/uncaught-referenceerror-ytcfg-is-not-defined
https://productforums.google.com/forum/#!topic/youtube/3Z7dSnwkCH4

**Comment by roncodingenthusiast** [comment]
Yhup I realised that just now. Thanks for the reply.

**Comment by ArunMichaelDsouza** [comment]
Sure no prob!
