### ISSUE TITLE
IE 11 - TypeError: Object doesn't support property or method 'includes'

### ISSUE THREAD

**Issue by Pseudo-Nym** [ArunMichaelDsouza/ng-youtube-embed#9]
The gaming URL fix seems to be causing issues in IE

TypeError: Object doesn't support property or method 'includes'
   at getVideoIdByUrl (http://xxx/ng-youtube-embed.js:91:13)
   at Anonymous function (http://xxx/ng-youtube-embed.js:245:25)
   at m.prototype.$digest (http://xxx/libs/angularjs/1.6.2/angular.min.js:145:373)
   at m.prototype.$apply (http://xxx/libs/angularjs/1.6.2/angular.min.js:148:339)
   at l (http://xxx/libs/angularjs/1.6.2/angular.min.js:101:87)
   at t.onload (http://xxx/libs/angularjs/1.6.2/angular.min.js:106:489)

91: var ytVideoRegex = url.**includes**('gaming') ? YOUTUBE_VIDEO_ID_REGEX_GAMING : YOUTUBE_VIDEO_ID_REGEX,

At this point in IE 
"&lt;div class="ng-binding" ng-bind-html="youtubeEmbedFrame"&gt;&lt;/div&gt;"
is not populated with iframe as expected ... everything still seems to work in other browsers.

Changing to:

var ytVideoRegex = **(url.indexOf('gaming') !== -1)** ? YOUTUBE_VIDEO_ID_REGEX_GAMING : YOUTUBE_VIDEO_ID_REGEX,

remedies the issue for me in IE 11 and still works in other browsers. Perhaps consider making this change to allow for backwards compatibility. I think that .includes() is not supported in IE until v12/MS Edge.

**Comment by ArunMichaelDsouza** [comment]
Hi @Pseudo-Nym, thanks for catching that. If you're willing to send in a PR to fix that real quick, that'd be great. I'll confirm and merge it in. 

Thanks.

**Comment by Pseudo-Nym** [comment]
@ArunMichaelDsouza PR added.

**Comment by ArunMichaelDsouza** [comment]
Fixed with your patch, released in the latest version - ``v1.7.9``. Thanks for contributing.
